### ISSUE TITLE
Some of Label Text is truncated 

### ISSUE THREAD

**Issue by jinyoung** [TheOpenCloudEngine/OpenGraph#1]
[Act] Ensure Stakeholder Satisfaction
[Act] Explorer Possibilities
[Act] Understand the Requirements

였어야 하는데, 아래 화면 처럼 나옴:

<img width="1354" alt="word" src="https://cloud.githubusercontent.com/assets/487999/20909940/e9672c9c-bba1-11e6-86b5-1b3da09eacb3.png">

**Comment by SeungpilPark** [comment]
Bug fixed.
